# Generated by Django 4.1.3 on 2022-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficienteA', models.IntegerField(verbose_name='coeficienteA')),
                ('coeficienteB', models.IntegerField(verbose_name='coeficienteB')),
                ('coeficienteC', models.IntegerField(verbose_name='coeficienteC')),
            ],
        ),
    ]
