# Generated by Django 4.1.3 on 2022-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_equacao_coeficientea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equacao',
            name='coeficienteA',
            field=models.BigIntegerField(verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='equacao',
            name='coeficienteB',
            field=models.BigIntegerField(verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='equacao',
            name='coeficienteC',
            field=models.BigIntegerField(verbose_name='c'),
        ),
    ]
