# Generated by Django 4.1.3 on 2022-11-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_equacao_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equacao',
            name='coeficienteA',
            field=models.BigIntegerField(default=0, null=True, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='equacao',
            name='coeficienteB',
            field=models.BigIntegerField(default=0, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='equacao',
            name='coeficienteC',
            field=models.BigIntegerField(default=0, null=True, verbose_name='c'),
        ),
    ]
